SELECT ROUND(35.5,-1);
SELECT ROUND(3.4999999);
SELECT CEIL(35.0000000001);
SELECT FLOOR(35.9);

SELECT UPPER(CONCAT("Hello", ", ", "World!"));
SELECT LPAD("Hello", 10, "*");
SELECT RPAD("Hello", 10, "*");
SELECT REPLACE("Hello", "H", "A");
SELECT SUBSTR("Hello", 2, 2); # 2에서 2개, SQL INDEX 1부터 시작
SELECT SUBSTR("안녕하세요", 2, 2);
SELECT CHAR_LENGTH("안녕하세요"); # 5
SELECT LENGTH("안녕하세요"); # 15 문자열의 BYTE를 반환 한글은 3BTYE
SELECT LENGTH(TRIM(" 안녕하세요"));

SELECT STR_TO_DATE("2025-10-02","%Y-%m-%d"); # 찍어보기 전까지는 출력형태만으로 자료형을 알 수 없음

SELECT * 
FROM ORDERS
WHERE ORDERDATE = STR_TO_DATE("2024-07-03","%Y-%m-%d");

SELECT DATE_FORMAT(ORDERDATE,"%Y-%m-%d")
FROM ORDERS;

SELECT ORDERDATE, ADDDATE(ORDERDATE, 1)
FROM ORDERS;

SELECT NOW();

SELECT CURDATE();

SELECT ADDDATE(CURDATE(), 14);

SELECT DATEDIFF("2025-09-30", ORDERDATE)
FROM ORDERS;

SELECT DATEDIFF(CURDATE(), "2025-09-30");

